using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BE=TrackerMVCEntities.BusinessEntities;
using DA = TrackerMVCDataLayer.Helper;
using DB = TrackerMVCDataLayer;

namespace TrackerMVCBusinessLayer.TrackerMVCBusinessManger
{
   public class IssuesTicket
    {
        string Issues = System.Configuration.ConfigurationSettings.AppSettings["IssuesTicket"].ToString();
        public List<BE.CompanyTicketInfo> AddCompanyticket(BE.CompanyTicketInfo ticket, string strAttachement, int companyid, string contentType, string CompanyName, string AddedDate,long Userid,int TicketNumber)
        {
            
            List<BE.CompanyTicketInfo> Companyticket = new List<BE.CompanyTicketInfo>();
            DataTable CreateUserDL = new DataTable();
            DA.DBOperations db = new DA.DBOperations();
            string UserName = "";
            string Location = "";
            DataTable dt1 = new DataTable();
            DataTable dt2 = new DataTable();
            dt1 = db.sub_GetDatatable("select u.UserName,C.con_Name from UserDetails u inner join Con_Details C on u.conid=c.Con_ID where UserID='" + Userid + "'");
            
            if (dt1.Rows.Count > 0)
            {
                UserName = Convert.ToString(dt1.Rows[0][0].ToString());
                ///Location = Convert.ToString(dt1.Rows[0][0].ToString());
            }

            dt2 = db.sub_GetDatatable("select C.ConCode from UserDetails u inner join Con_Details C on u.conid=c.Con_ID where UserID='" + Userid + "'");

            if (dt2.Rows.Count > 0)
            {
                //UserName = Convert.ToString(dt1.Rows[0][0].ToString());
                Location = Convert.ToString(dt2.Rows[0]["ConCode"].ToString());
            }

            string SendTO = ticket.MailID;
            string strText = "";
            string strtable = "";

            string  Subject = "New Ticket Generated from  " + TicketNumber + " "+ ticket.Subject;

            
            strText += "<font face='Calibri' color='black' size=3> New ticket no " + TicketNumber + " Generated by "+ UserName + " Please Check  </font> <br>";
            strtable += "<html><body>";
            strtable += "<table align='left' cellpadding='0' cellspacing='0' bordercolor='black'   Style='width: 100%; height: auto;'>  ";
            strtable += "<tr bgcolor='white'><font face='Calibri' color='black' size='3'> <td style='padding-left: 10px; padding-bottom: 05px; padding-top: 05px; padding-right: 20px;'>" + strText + "<br> </td></tr>";
            strtable += "</table>";
            strtable += "<table align='left' cellpadding='0' cellspacing='0' bordercolor='black'  border='1' Style='width: 50%; height: auto;'>  ";

            strtable += "<tr bgcolor='white'><td style='padding-left: 10px; padding-bottom: 05px; padding-top: 05px; padding-right: 20px;'>Ticket Date : " + AddedDate + " </td></tr>";
            strtable += "<tr bgcolor='white'><td style='padding-left: 10px; padding-bottom: 05px; padding-top: 05px; padding-right: 20px;'>Location     :" + Location + " </td></tr>";
            strtable += "<tr bgcolor='white'><td style='padding-left: 10px; padding-bottom: 05px; padding-top: 05px; padding-right: 20px;'>Description : " + ticket.Description + "</td></tr>";

            strtable += "</table>";
            strtable += "</body></html>";

           
            DataTable dt = new DataTable();
            dt = db.sub_GetDatatable("Usp_Mail_Settings_Date_Fill '" + Issues + "'");

            if(dt != null)
            {
                if (dt.Rows.Count > 0)
                {
                    BE.EmailHelper obj = new BE.EmailHelper();
                    Boolean edata = obj.SendEMail(Convert.ToInt32(dt.Rows[0]["SMTPServerPort"]), dt.Rows[0]["SMTPServer"].ToString(), dt.Rows[0]["MailFromID"].ToString(), dt.Rows[0]["UserPassword"].ToString(), dt.Rows[0]["MailTo"].ToString(),Subject, strtable, dt.Rows[0]["MailCC"].ToString(), dt.Rows[0]["MailBCC"].ToString(), strAttachement);
                }
            }
 

            DB.TrackerMVCDBManager trackerdatamanager = new DB.TrackerMVCDBManager();

            CreateUserDL = trackerdatamanager.AddCompanyTicketDetails1(ticket.Description, ticket.MailID, strAttachement, companyid, contentType, Userid, TicketNumber);
            

            return Companyticket;
        }

    }


}
